version: '2'
services:
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DATABASE_URI: postgres://username:s0me-p4sswd@host:port/db
  postgres:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: s0me-p4sswd
      POSTGRES_DB: db
      # POSTGRES_PORT: 5432
